#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2024 Dave Conroy <dave@tiredofit.ca>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
PROCESS_NAME="peertube"

prepare_service
check_container_initialized
check_service_initialized init
liftoff

cd /app

export HOME=/tmp/
export NODE_ENV=production
export NODE_CONFIG_DIR=${CONFIG_PATH}
export PEERTUBE_LOCAL_CONFIG=${CONFIG_PATH}

print_start "Starting Peertube ${PEERTUBE_VERSION}"
exec s6-setuidgid peertube node dist/server
